// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cpu": {
            "get": {
                "description": "Returns the current CPU usage percentage measured over a 1-second interval",
                "produces": [
                    "application/json"
                ],
                "summary": "Get CPU usage",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CpuResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/hello": {
            "get": {
                "description": "Returns a simple greeting message",
                "produces": [
                    "application/json"
                ],
                "summary": "Get a hello message",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.HelloResponse"
                        }
                    }
                }
            }
        },
        "/memory": {
            "get": {
                "description": "Returns details about the virtual memory usage of the system (total, used, available, etc.)",
                "produces": [
                    "application/json"
                ],
                "summary": "Get memory statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MemoryResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ws": {
            "get": {
                "description": "Upgrades the HTTP connection to a WebSocket. The server periodically broadcasts system memory stats (as WebsocketResponse) every 5 seconds. Connect via ws://localhost:8081/ws",
                "summary": "Establish WebSocket connection",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Upgrade",
                        "description": "Upgrade",
                        "name": "Connection",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "websocket",
                        "description": "websocket",
                        "name": "Upgrade",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "101": {
                        "description": "Switching Protocols",
                        "schema": {
                            "$ref": "#/definitions/models.WebsocketResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.CpuResponse": {
            "type": "object",
            "properties": {
                "usage": {
                    "type": "number"
                }
            }
        },
        "models.HelloResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "models.MemoryResponse": {
            "type": "object",
            "properties": {
                "available": {
                    "type": "integer"
                },
                "availableGb": {
                    "type": "number"
                },
                "total": {
                    "type": "integer"
                },
                "totalGb": {
                    "type": "number"
                },
                "used": {
                    "type": "integer"
                },
                "usedGb": {
                    "type": "number"
                },
                "usedPercent": {
                    "type": "number"
                }
            }
        },
        "models.WebsocketResponse": {
            "type": "object",
            "properties": {
                "payload": {
                    "$ref": "#/definitions/models.MemoryResponse"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Go System Stats API",
	Description:      "A simple Go API that provides CPU and Memory statistics, and a WebSocket stream.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
